name: horoscope_dribble_app
description: An horoscope app based on https://dribbble.com/shots/14168746-Astrology-Horoscope-App

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  rxdart: ^0.25.0
  sensors: '>=0.4.2+6 <2.0.0'
  domain:
    path: ./domain
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true